# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Data Science: Mingled with Sports"
email: ml636@byu.edu
description: "This is a data science blog that discusses basic statistics and data science topics. I also have a love for sports that will often find its way into mt posts." 
baseurl: "/stat386-blog-theme" # the name of the repository 
url: "https://MattLindeman.github.io" #  change this to "https://<your-github-username>.github.io"
image: https://unsplash.com/photos/y2azHvupCVo
author: Matt Lindeman
copyright: ML # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description:


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username:
github_username: MattLindeman
linkedin_username: linkedin.com/in/matt-lind/
dribbble_username: 
facebook_username: 
flickr_username:
instagram_username: 
pinterest_username:
youtube_username: 
googleplus_username:

plugins:
  - jekyll-feed

